MODEL:
  PRETRAIN_PATH: './modeling/resnet50-19c8e357.pth'
  PRETRAIN_CHOICE: 'imagenet'
  METRIC_LOSS_TYPE: 'triplet_center'
  IF_LABELSMOOTH: 'on'
  IF_WITH_CENTER: 'yes'

INPUT:
  SIZE_TRAIN: [256, 256]
  SIZE_TEST: [256, 256]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  #COLORJITTER: False  # for model ensemble
  
DATASETS:
  NAMES: ('UAM')
  ROOT_DIR: 'local rute to dataset...../ICIP_UrbAM-ReID/splits/Containers/containers/'

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8
  #SOFT_MARGIN: False # for model ensemble

SOLVER:
  OPTIMIZER_NAME: 'Adam'
  MAX_EPOCHS: 100
  BASE_LR: 0.00035 #0.00035
  CENTER_LR: 0.5
  CENTER_LOSS_WEIGHT: 0.0005
  CLUSTER_MARGIN: 0.3

  RANGE_K: 2
  RANGE_MARGIN: 0.3
  RANGE_ALPHA: 0
  RANGE_BETA: 1
  RANGE_LOSS_WEIGHT: 1
  BIAS_LR_FACTOR: 1
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 70]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10
  WARMUP_METHOD: 'linear'

  CHECKPOINT_PERIOD: 10
  LOG_PERIOD: 5
  EVAL_PERIOD: 105

TEST:
  IMS_PER_BATCH: 128
  WEIGHT: "path"
  RE_RANKING: 'no'
  NECK_FEAT: 'after'
  FEAT_NORM: 'yes'
OUTPUT_DIR: "./tools/checkpoints/"


